# Generated by Django 4.2.5 on 2023-09-20 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(default="Naif", max_length=30)),
                ("hotel_owner", models.CharField(max_length=20)),
                ("hotel_location", models.CharField(max_length=50)),
                ("hotel_state", models.CharField(default="Dubai", max_length=50)),
                ("hotel_country", models.CharField(default="UAE", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("1", "Suite"),
                            ("2", "Penthouse"),
                            ("3", "Quad Bedroom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("max_capacity", models.IntegerField()),
                ("room_price", models.IntegerField()),
                ("room_size", models.IntegerField()),
                (
                    "availability_status",
                    models.CharField(
                        choices=[("1", "Available"), ("2", "Not Available")],
                        max_length=15,
                    ),
                ),
                ("room_number", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hotels"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("booking_id", models.CharField(default="null", max_length=100)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.rooms"
                    ),
                ),
            ],
        ),
    ]
